### ISSUE TITLE
Unsupported operand error in wikibase.revision.diff.properties_diff

### ISSUE THREAD

**Issue by halfak** [wiki-ai/revscoring#239]
Getting the following error when trying to extract anything the depends on \<wikibase.revision.diff.properties_diff\>.  

```
$ echo -e "221842942\tFalse" | revscoring extract_features demo_features.fails --host https://wikidata.org 
2016-02-07 22:03:43,661 ERROR:revscoring.utilities.extract_features -- An error occured while processing 221842942:
2016-02-07 22:03:43,661 ERROR:revscoring.utilities.extract_features -- 	CaughtDependencyError: TypeError: Failed to process <wikibase.revision.diff.properties_diff>: unsupported operand type(s) for /: 'NoneType' and 'float'
```

The `demo_features.fails` contains the following python
```python
from revscoring.features import wikibase

fails = [wikibase.revision.diff.properties_added]
```

**Comment by halfak** [comment]
Here's a more thorough error message.  It looks like this issue is in pywikibase. 

```
Traceback (most recent call last):
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/revscoring-1.0.0rc1-py3.4.egg/revscoring/dependencies/functions.py", line 235, in _solve
    value = dependent(*args)
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/revscoring-1.0.0rc1-py3.4.egg/revscoring/dependencies/dependent.py", line 52, in __call__
    return self.process(*args, **kwargs)
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/revscoring-1.0.0rc1-py3.4.egg/revscoring/features/wikibase/util.py", line 54, in diff_dicts
    if a[key] == b[key]:
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/claim.py", line 155, in __eq__
    return other.toJSON() == self.toJSON()
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/claim.py", line 176, in toJSON
    data['mainsnak']['datavalue'] = self._formatDataValue()
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/claim.py", line 419, in _formatDataValue
    return {'value': self._formatValue(),
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/claim.py", line 406, in _formatValue
    value = self.getTarget().toWikibase()
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/coordinate.py", line 93, in toWikibase
    'precision': self.precision,
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/pywikibase/coordinate.py", line 140, in precision
    self._dim / (radius * math.cos(math.radians(self.lat))))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

I'm running pywikibase 0.0.3

```
$ pip freeze | grep pywikibase
pywikibase==0.0.3
```

**Comment by Ladsgroup** [comment]
Fixed at https://gerrit.wikimedia.org/r/#/c/269087/

**Comment by he7d3r** [comment]
Closing per https://github.com/wiki-ai/revscoring/issues/239#issuecomment-181252974
